version: "3"
#
networks:
  default:
    driver: bridge
  kong-network:
    external:
      name: kong-network
  kong-proxy:
    external:
      name: kong-proxy
#
services:
  #
  #######################################
  # PostgreSql: The database used by Kong
  #######################################
  kong_database:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - ./postgres/kong_database:/var/lib/postgresql/data
    environment:
      TZ: Asia/Bangkok
      POSTGRES_DB: kong_cp
      POSTGRES_USER: kong_cp
      POSTGRES_PASSWORD: kong_cp
      POSTGRES_HOST_AUTH_METHOD: trust
  #
  #######################################
  # Kong: database migration
  #######################################
  kong_cp_migration:
    image: kong:2.6
    depends_on:
      - kong_database
    command: kong migrations bootstrap
    restart: on-failure
    environment:
      TZ: Asia/Bangkok
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_database
      KONG_PG_DATABASE: kong_cp
      KONG_PG_USER: kong_cp
      KONG_PG_PASSWORD: kong_cp
  #
  #######################################
  # Kong gen cert
  #######################################
  # kong_gen_cert:
  #   image: kong:2.6
  #   depends_on:
  #     - kong_cp_migration
  #   command: kong hybrid gen_cert --v
  #   working_dir: /certs
  #   volumes:
  #     - ./kong-certs:/certs:rw
  #   environment:
  #     - TZ=Asia/Bangkok
  #
  #######################################
  # Kong: The API Gateway
  #######################################
  kong_cp:
    image: kong:2.6
    depends_on:
      - kong_cp_migration
      # - kong_gen_cert
    restart: always
    volumes:
      - ./kong-certs:/certs:ro
    environment:
      TZ: Asia/Bangkok
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr

      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_STATUS_LISTEN: 0.0.0.0:9123

      KONG_ROLE: control_plane
      KONG_CLUSTER_CERT: /certs/cluster.crt
      KONG_CLUSTER_CERT_KEY: /certs/cluster.key

      KONG_DATABASE: postgres
      KONG_PG_HOST: kong_database
      KONG_PG_DATABASE: kong_cp
      KONG_PG_USER: kong_cp
      KONG_PG_PASSWORD: kong_cp
    ports:
      - 8001:8001
      - 8444:8444
    networks:
      - default
      - kong-network
  #
  kong_dp:
    image: kong:2.6
    depends_on:
      - kong_cp
    restart: always
    volumes:
      - ./kong-certs:/certs:ro
    environment:
      TZ: Asia/Bangkok
      KONG_DATABASE: "off"

      KONG_PROXY_ACCESS_LOG: "/dev/stdout custom_format"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_NGINX_HTTP_LOG_FORMAT: |
        custom_format escape=none 'time_local ==> [$$time_local] \n remote_addr ==> $$remote_addr \n http_x_forwarded_for ==> $$http_x_forwarded_for \n status ==> $$status \n request ==> $$request \n body_bytes_sent ==> $$body_bytes_sent \n request_body ==> $$request_body \n http_referer ==> $$http_referer \n http_user_agent ==> $$http_user_agent'
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_STATUS_LISTEN: "0.0.0.0:9123"

      KONG_ROLE: "data_plane"
      KONG_CLUSTER_CONTROL_PLANE: "kong_cp:8005"
      KONG_CLUSTER_CERT: "/certs/cluster.crt"
      KONG_CLUSTER_CERT_KEY: "/certs/cluster.key"
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: "/certs/cluster.crt"
    ports:
      - 8000:8000
      - 8443:8443
    networks:
      - default
      - kong-proxy
